import os
from rdkit import Chem
from rdkit.Chem import AllChem, SDWriter, Draw

TEMP_DIR = "temp_files"
if not os.path.exists(TEMP_DIR):
    os.makedirs(TEMP_DIR)

# InChi --> Smiles
def inchi_to_smiles(inchi_string):
    mol = Chem.MolFromInchi(inchi_string)
    return Chem.MolToSmiles(mol)

# InChi --> SDF (Visualization)
def inchi_sdf_visualize(inchi_string):
    mol = Chem.MolFromInchi(inchi_string)
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    AllChem.UFFOptimizeMolecule(mol)
    
    sdf_file = os.path.join(TEMP_DIR, 'output.sdf')
    writer = SDWriter(sdf_file)
    writer.write(mol)
    writer.close()

    img = Draw.MolToImage(mol, size=(300, 300))
    image_file = os.path.join(TEMP_DIR, 'output_image.png')
    img.save(image_file)

    return sdf_file, image_file

# InChi --> XYZ (Visualization)
def inchi_to_xyz_visualize(inchi_string):
    mol = Chem.MolFromInchi(inchi_string)
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    AllChem.UFFOptimizeMolecule(mol)
    
    xyz_file = os.path.join(TEMP_DIR, 'output.xyz')
    with open(xyz_file, 'w') as f:
        f.write(f"{mol.GetNumAtoms()}\n")
        f.write("Generated by RDKit\n")
        for atom in mol.GetAtoms():
            pos = mol.GetConformer().GetAtomPosition(atom.GetIdx())
            f.write(f"{atom.GetSymbol()} {pos.x:.4f} {pos.y:.4f} {pos.z:.4f}\n")
    
    img = Draw.MolToImage(mol, size=(300, 300))
    image_file = os.path.join(TEMP_DIR, 'output_image.png')
    img.save(image_file)

    return xyz_file, image_file